[package]
name = "ldbc_snb"
version = "0.1.0"
authors = ["Tamas Nyiri <info@nyiritamas.hu>"]
edition = "2018"

[dependencies]
chrono = "~0.4.10"
differential-dataflow = "~0.11.0"
timely = "~0.11.1"
named_tuple = "~0.1.3"
